name: go

on:
  push:
    branches:
      - master
    tags:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Linters (Static Analysis) for Go
    env:
      GOBIN: /tmp/.bin
    steps:
      - name: Checkout code into the Go module directory.
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x

      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Format.
        run: make format

      - name: Linting & vetting.
        run: make go-lint